# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#

version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
  build2:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: 
          name: Get Submodule 
          command: |
            git submodule sync
            git submodule update --init
workflows:
  version: 2
  build_and_buil2:
    jobs:
      - build
      - build2:
          requires:
            - build
          filters:
            branches:
              only: master